---

- hosts: all
  become: true
  tasks:

  - name: Install Apache and php 
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes

#  - name: update firewall on RedHat/Centos
#  - name: start httpd on RedHat/Centos
    

