---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache2 and php package for RedHat/Centos
    dnf:
      name: 
        - httpd
        - php, php-mysqlnd, php-pdo, php-gd, php-mbstring 
      state: absent
      update_cache: yes
    when: ansible_distribution in ["RedHat", "Centos"]

  - name: remove Apache2 and php package for Debian/Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

#  - name: update firewall on RedHat/Centos
#  - name: start httpd on RedHat/Centos
    

