---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes      

  - name: Remove Apache2 package
    dnf:
      name: httpd
      state: absent

  - name: remove php support for apache
    dnf:
      name: php, php-mysqlnd, php-pdo, php-gd, php-mbstring 
      state: absent
