---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution in [ "RedHat", "CentOS" ]

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu", "Debian" ]

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    package:
      name: 
        - apache2 
        - libapache2-mod-php 
      state: latest
    when: ansible_distribution in [ "Ubuntu", "Debian" ]

  - name: Install Apache and php for RedHat servers
    tags: apache,apache2,redhat
    package:
      name: 
        - httpd 
        - php 
      state: latest
    when: ansible_distribution in [ "RedHat", "CentOS" ]

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks: 
  
  - name: install mariadb package (RedHat)
    tags: db,mariadb,redhat
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in [ "RedHat", "CentOS" ]

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in [ "Ubuntu", "Debian" ]
     
- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package (ALL) 
    tags: samba,all
    package:
      name: samba
      state: latest
  
