
- name: Install Apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  package:
    name: 
      - apache2 
      - libapache2-mod-php 
    state: latest
  when: ansible_distribution in [ "Ubuntu", "Debian" ]

- name: Install Apache and php for RedHat servers
  tags: apache,apache2,redhat
  package:
    name: 
      - httpd 
      - php 
    state: latest
  when: ansible_distribution in [ "RedHat", "CentOS" ]

- name: start httpd(RedHat/CentOS_
  tags: apache,apache2,redhat,httpd,centos
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in [ "RedHat", "CentOS" ]
 
- name: change e-mail address for admin
  tags: apache,apache2,httpd
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution in [ "RedHat", "CentOS" ]
  register: httpd

- name: restart httpd (CentOS/Redhat)     
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
